#!/usr/bin/env node
// Generates dist/theme.css and dist/fonts.css from the compiled theme data
// (dist/themes.js). Run after tsc — `npm run build` chains it.
//
// dist/theme.css is generated to be byte-identical to the theme.css that
// shipped in lunatwo ui/src (design_handoff_theming) at the moment of the v0.2
// lift — that identity is the proof the codegen is faithful. From v0.2 on,
// themes.ts is the source; never hand-edit the CSS.

const fs = require('fs');
const path = require('path');
const { themes } = require('../dist/themes.js');

const out = (name, content) =>
  fs.writeFileSync(path.join(__dirname, '..', 'dist', name), content);

const vars = (t) => ({
  '--bg': t.bg,
  '--surface': t.surface,
  '--surface-border': t.surfaceBorder,
  '--ink': t.ink,
  '--ink-muted': t.inkMuted,
  '--brief-bg': t.briefBg,
  '--brief-border': t.briefBorder,
  '--accent': t.accent,
  '--accent-strong': t.accentStrong,
  '--link-underline': t.linkUnderline,
  '--empty-bg': t.emptyBg,
  '--empty-fg': t.emptyFg,
});

const laneLines = (t, pad = '  ') =>
  [
    `${pad}--lane-thinking-bg: ${t.lanes.thinking.bg}; --lane-thinking-fg: ${t.lanes.thinking.fg};`,
    `${pad}--lane-doing-bg: ${t.lanes.doing.bg};    --lane-doing-fg: ${t.lanes.doing.fg};`,
    `${pad}--lane-queued-bg: ${t.lanes.queued.bg};   --lane-queued-fg: ${t.lanes.queued.fg};`,
  ].join('\n');

const legacyRemap = (t) =>
  [
    '  --cream-bg: var(--bg);',
    '  --cream-light: var(--surface);',
    `  --cream-dark: ${t.creamDark};`,
    '  --font-main: var(--font-body);',
    '  --warm-red: var(--accent);',
  ].join('\n');

const block = (t) =>
  Object.entries(vars(t))
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');

const r = themes.rainbow;
const l = themes.light;
const d = themes.dark;

const themeCss = `/* Luna 2.0 — theme token contract (design_handoff_theming).
 *
 * Three switchable themes from one token contract:
 *   - light   (Light & Airy)
 *   - dark
 *   - rainbow (Bold & Beautiful — the DEFAULT, Shelley's theme)
 *
 * Mechanism: data-theme="light|dark|rainbow" on <html>. Rainbow's tokens also
 * live on bare :root so the app is correctly themed before JS runs (no flash).
 *
 * Type is per-theme (intentional — the rainbow theme has its own expressive
 * voice): --font-display / --font-body are set in each block, not just colors.
 *
 * GENERATED by @lunamonster/luna-design (scripts/generate-css.cjs) from
 * themes.ts — do not hand-edit. The legacy shell variables (--cream-bg,
 * --cream-light, --font-main, --warm-red) are remapped per theme so a theme
 * swap re-skins the global surfaces + typography.
 */

/* ============================ RAINBOW (default) ============================ */
:root,
:root[data-theme='rainbow'] {
${block(r)}

  /* Faint full-spectrum board wash over the base surface. */
  --board-wash: ${r.boardWash};

  /* Lane tokens (Thinking / Doing / Queued). */
${laneLines(r)}

  /* Per-theme type — Rainbow: brush display + Safira March body. */
  --font-display: ${r.fontDisplay};
  --font-body: ${r.fontBody};

  /* Legacy shell remaps so existing var() usages pick up the theme. */
${legacyRemap(r)}
}

/* ============================ LIGHT & AIRY ================================ */
:root[data-theme='light'] {
${block(l)}
  --board-wash: ${l.boardWash};

${laneLines(l)}

  /* Light & Airy: Safira March display + Cairo body (no script/handwriting). */
  --font-display: ${l.fontDisplay};
  --font-body: ${l.fontBody};

${legacyRemap(l)}
}

/* ================================= DARK =================================== */
:root[data-theme='dark'] {
${block(d)}
  --board-wash: ${d.boardWash};

${laneLines(d)}

  /* Dark: Safira March display + Cairo body. */
  --font-display: ${d.fontDisplay};
  --font-body: ${d.fontBody};

${legacyRemap(d)}
}

/* Global surfaces read straight from the tokens so a swap is immediate. */
html { background: var(--bg); }
body {
  background: var(--bg);
  color: var(--ink);
  font-family: var(--font-body);
}
/* Rainbow's faint spectrum wash over the base board. */
:root[data-theme='rainbow'] body { background-image: var(--board-wash); background-attachment: fixed; }
`;

const fontsCss = `/* Luna — self-hosted fonts, shipped by @lunamonster/luna-design (fonts/).
 * GENERATED (scripts/generate-css.cjs) — do not hand-edit.
 * Licensed faces (Safira March, Stay Dreaming Alt) are NOT on any CDN and must
 * be served from these files — never rely on a font being installed. License
 * for private-package redistribution confirmed 2026-07-18.
 * Paths are relative to dist/ (bundlers resolve ../fonts within the package).
 */

/* Rainbow theme display (brush) — licensed */
@font-face {
  font-family: 'Stay Dreaming Alt';
  src: url('../fonts/StayDreamingAlt.ttf') format('truetype');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}

/* Light/Dark display · Rainbow body — licensed (thin master; 100–400 range) */
@font-face {
  font-family: 'Safira March';
  src: url('../fonts/SafiraMarch-Thin.ttf') format('truetype');
  font-weight: 100 400;
  font-style: normal;
  font-display: swap;
}

/* Light/Dark body — self-hosted copy of Cairo (also free on Google Fonts) */
@font-face {
  font-family: 'Cairo';
  src: url('../fonts/Cairo.woff2') format('woff2');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}

/* Western Sans — self-hosted (woff2 → woff → otf fallback) */
@font-face {
  font-family: 'Western Sans';
  src: url('../fonts/WesternSans-Regular.woff2') format('woff2'),
       url('../fonts/WesternSans-Regular.woff') format('woff'),
       url('../fonts/WesternSans-Regular.otf') format('opentype');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}

/* Semantic aliases for the theme system to consume via font-family: var(--font-*). */
:root {
  --font-display-brush: 'Stay Dreaming Alt', 'Caveat Brush', cursive;
  --font-display-elegant: 'Safira March', 'Poppins', sans-serif;
  --font-body-cairo: 'Cairo', -apple-system, BlinkMacSystemFont, sans-serif;
  --font-western: 'Western Sans', -apple-system, BlinkMacSystemFont, sans-serif;
}
`;

out('theme.css', themeCss);
out('fonts.css', fontsCss);
console.log('generated dist/theme.css + dist/fonts.css');
